# Generated by Django 4.2.14 on 2024-08-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
